### PR TITLE
remove React argument and use peerDependencies

### PR DESCRIPTION
**Pull request by iRON5**
I noticed that the hook requires React instance as an argument but it is already included to `peerDependencies` in `package.json`.

So there is no need to pollute arguments and it is possible to import React directly.

**Breaking change**: remove React from hook arguments

### CODE REVIEW

**Comment by rickstaa** [comment]
@iRON5 This is exactly why I was hesitant to use this hook on my projects. The React input argument looked strange. Maybe it was needed in the past? Can somebody of the @use-global-hook organization maybe check if this can be merged?

**Review by davityavryan — CHANGES_REQUESTED** [review]
Thanks @iRON5 
Would you be so kind to update documentation file(s) too?

**Comment by iRON5** [comment]
> Thanks @iRON5
> Would you be so kind to update documentation file(s) too?

Done

**Review by davityavryan — APPROVED** [review]
👍

**Comment by davityavryan** [comment]
released a breaking change as `use-global-hook@0.3.0`

**Pull request merged**
