### PR TITLE
Allow the ability to set references

### PR DESCRIPTION
**Pull request by nmccready**
This is important if your hook is being set by `<SomeComponent "ref={actions.setRef}" />`

### CODE REVIEW

**Comment by squarebraket** [comment]
Could you explain why is this needed, perhaps using an example? I fail to understand when and how this would be needed and used.

Thanks

**Comment by nmccready** [comment]
It is needed because `ref` in react requires a real Dom element. If you use `setState` it uses the spread operator which strips many of Elements functions, prototypes etc.  Lastly, at times you can think of setRef as a `reset`.  There are times where you need to start over from scratch on the base state of the internal store.

**Comment by nmccready** [comment]
In a nutshell I have a dom element that is being shared among many components (joining react code to jquery) it easier to use a global-hook ("context") like element than pass this down to everything with more properties. This hook state is initially set by `<SomeComponent ref={elementActions.setRef} />` .

**Comment by andregardi** [comment]
I still don't understand.
Did you try to put your ref inside an object before set it into the state?
Reading the new code, it will work as if your whole state is just one ref. Was that the idea?

Can you make a sandbox for us with a minimal example?

**Comment by nmccready** [comment]
I'll make something on CodePen tomorrow. Have you ever used `ref=""` on element in React b4? If so just go ahead and try storing off that element with your `setState`. You will see that it fails as it attempts to clone the DomElements properties which are all prototypes. 

In essence you can't expect to always due shallow clones and should allow for real references and possible deep clones.

**Comment by nmccready** [comment]
@andregardi Here is the simple example showing the problem clearly .
https://codepen.io/nmccready/pen/vYBgrGR

**Comment by andregardi** [comment]
Did you try?
```javascript
const useGlobalRef = UseGlobalHook({ React });
const useGlobalRefWState = UseGlobalHook({ React });

const RefProvider = () => {
  const [, { setRef }] = useGlobalRef();
  const [, { setState }] = useGlobalRefWState();
  const element = React.useRef(null);
  return React.useMemo(() => {
    setTimeout(() => {
      setRef({ ref: element.current });
      setState({ ref: element.current });
    }, 500);
    return <p ref={element}>RefProvider</p>;
  }, [setRef, setState]);
};

const RefConsumer = ({ globalHook }) => {
  const [state] = globalHook();
  console.log(state);
  const ref = state && state.ref;
  return (
    <div>
      <p>RefConsumer</p>
      {!ref ? (
        "Not Set"
      ) : (
        <div style={{ marginLeft: 10 }}>
          InnerText:
          <strong style={{ marginLeft: 10 }}>
            {ref.innerText
              ? ref.innerText
              : "oh look I am missing didn't use ref"}
          </strong>
        </div>
      )}
    </div>
  );
};

const App = () => {
  return (
    <div className="box">
      <RefProvider />
      <RefConsumer globalHook={useGlobalRef} />
      <RefConsumer globalHook={useGlobalRefWState} />
    </div>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));

```

**Comment by nmccready** [comment]
Yes I did see I could do it that way. But that's not the point. The point is that ref should be allowed to not have to have nested fields to keep refs. Anyway if setRef is is in React it seems to me it should be here as well.

**Pull request closed without merging**
