### PR TITLE
Fixed #23

### LINKED ISSUE #23: Double render on react-native
Hi, 
First or all, thanks a lot for your work.
Do you experience a double render instead of one in react-native? With other hooks, like useState, I get one render, but with this, I get another render out of nowhere. 
**It happens only when the component is being mount the first time, in every single component.**
Also, if you use 2/3/4/X of your hooks in the component, it doesn't matter. It still render two times.

```
import React from "react";
import { AppRegistry, View } from 'react-native';
import App from './app/App';
import { name as appName } from './app.json';
import { useSettings } from "./app/store";

AppRegistry.registerComponent(appName, () => function(){
    const [, setTheme] = useSettings(
        state => undefined,
        actions => actions.setTheme
    );
    console.log("render");
    return <View></View>;
});
```

You can test it even on the index.js of a the project (my useSettings hook is almost the same of your useGlobal example).

Is it normal? Because I tried it on React and it seems to not double render.

Thanks,
Nicholas Bertazzon.

### PR DESCRIPTION
**Pull request by nodtem66**
Double-rendering problem in #23
https://codesandbox.io/s/4h3n3

The proposed solution is changing 
`React.useState(Object.create(null));` to `React.useState(state);`

### CODE REVIEW

**Comment by s-KaiNet** [comment]
According to react [docs](https://reactjs.org/docs/hooks-reference.html#bailing-out-of-a-state-update) 
> Note that React may still need to render that specific component again before bailing out. That shouldn’t be a concern because React won’t unnecessarily go “deeper” into the tree.  

Will it be safer just use `const newListener = { oldState: state };` on line [`18`](https://github.com/andregardi/use-global-hook/blob/master/index.js#L18)?  
 

Alternatively, can we just remove [this line](https://github.com/andregardi/use-global-hook/blob/master/index.js#L29), because it causes to double render?

**Comment by nodtem66** [comment]
@s-KaiNet, IMHO, I'd like to remove https://github.com/andregardi/use-global-hook/blob/b419233647c320e7eb92bc0553f81d45db8968c1/index.js#L29
As you said, it caused the double rendering

**Comment by meistersodatim** [comment]
> Double-rendering problem in #23
> https://codesandbox.io/s/4h3n3

It's not happening in your sandbox. But if I use it in my own project, it renders twice. Commenting out 
newListener.run(store.state); 
as proposed cuts rerendering from 4 times to 2 times.

**Comment by andregardi** [comment]
Thank you for that!
Sorry for the delay. I am going to make some more tests and add to the next release.

**Pull request merged**
